### ISSUE TITLE
Illinois attribute is causing color issues with hero, content, etc. 

### ISSUE THREAD

**Issue by bryanjonker-illinois** [web-illinois/ilw-page#2]
![Screenshot 2024-07-17 100925](https://github.com/user-attachments/assets/d6d5c99f-a319-4cb0-a506-54564ad98b1c)

**Comment by marvel-uiuc** [comment]
@bryanjonker-illinois I think the way I would solve this issue is:

Apply CSS properties like `color` only once for the whole component and set them to a variable like `ilw-page--text-color`. Then with themes, only override the variable, not the CSS property. The variables can also be set in a layer, that way if the component user sets the variable specifically to something else, it'll take precedence. However, since the `color` property is set not in a layer, it won't be accidentally overridden by parent styles.

For example, the way I did it with ilw-card:

```css
@layer base {
  :root {
    --ilw-card--text-color: var(--ilw-text--color); /*var: Color of text in the card*/
  }
  ilw-card[theme="orange"] {
    --ilw-card--text-color: var(--il-blue);
  }
}
ilw-card {
  color: var(--ilw-card--text-color);
}
```

Another benefit of this approach is that when components use other components as children. The child component's colors are set in the `:root`. When it doesn't have a specific theme, the parent component can set those variables when they're intended to be used together. In the case of ilw-card, the themes set the button color variables, but if the button itself has a specific theme, that more specific theme takes precedence.

This may be one of those cases where we need to be more practical than ideal, but I thought I'd at least throw it out there.
